import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {children}</body>
    </html>
  )
}
// step 6 privers ko import kr ke   childeren ko ander rap kr dya 
// ab sara store layout ke ander agaya hai ab hum pure project me easily use kr sakte hai